name: Build and bundle

on:
   push:
      branches: ['main']
   pull_request:
      branches: ['main']

jobs:
   package:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v3
           with:
              node-version: 18
         - name: Install dependencies
           run: npm ci

         - name: Bundle editor extension
           run: npm run bundle

         - name: Upload artifact
           uses: actions/upload-artifact@v2
           with:
              name: Bundle
              path: package.zip
