name: Build and bundle

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v2
              with:
                    node-version: 18
            - name: Install dependencies
              run: npm ci && cd editorExtensions/codebeamer-custom-ui/modal && npm ci && cd ../../..

            - name: Build custom UI
              run: cd editorExtensions/codebeamer-custom-ui/modal && npm run build && cd ../../..

            - name: Bundle editor extension
              run: npm run bundle
            
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: package
                path: package.zip

