on:
    push:
        branches:
            - 'feature/**'
        paths:
            - '**.ts'
            - '**.tsx'
    pull_request:
        branches:
            - 'develop'
            - 'feature/**'
        paths:
            - '**.ts'
            - '**.tsx'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install modules
          run: npm ci
        - name: Run ESLint
          run: eslint . --ext .ts,.tsx