name: Test

on:
   push:
      branches: [main, develop, oauth-prototype]
   pull_request:
      branches: [main, develop, oauth-prototype]

jobs:
   test:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: '14'

         - name: run tests
           run: cd dataconnectors/codebeamer && npm install && npm test
